dnmonster:
    image: amouat/dnmonster:1.0

identidock:
    build: .
    ports: 
        - "3000:5000"
    environment: 
        ENV: DEV
    volumes:
        - ./app:/app
    links:
        - dnmonster

